"""GitHub profile banner, DHAHAB identity.

Composes the lion mark from the canonical generator (read-only import of
tools/brand/lion.py in the portfolio repo) so the geometry stays byte-identical
with every other surface. Two variants: dark (ink ground, GitHub default) and
light, switched in the README via <picture> prefers-color-scheme.

    python3 assets/banner.py
"""
import os
import sys

BRAND_DIR = os.environ.get(
    "DHAHAB_BRAND_DIR", os.path.expanduser("~/Yusuf-Gadelrab.github.io/tools/brand")
)
sys.path.insert(0, BRAND_DIR)

try:
    from lion import BONE, GOLD, INK, mark  # noqa: E402
except ImportError:  # pragma: no cover
    sys.exit(
        f"lion.py not found in {BRAND_DIR}.\n"
        "The mark is generated by the canonical brand generator, kept in the "
        "portfolio repo so every surface shares one geometry:\n"
        "  https://github.com/Yusuf-Gadelrab/Yusuf-Gadelrab.github.io "
        "(tools/brand/lion.py)\n"
        "Point DHAHAB_BRAND_DIR at that directory and re-run. "
        "The committed SVGs in this folder are the output of this script."
    )

HERE = os.path.dirname(os.path.abspath(__file__))
W, H = 1400, 360


def banner(dark=True):
    ground = INK if dark else "#f7f3ec"
    name_fill = BONE if dark else INK
    # GOLD is 1.9:1 on the cream ground — fine for the mark and rules, too weak
    # for the tagline. Deep antique gold instead: 4.7:1, passes WCAG AA.
    tag_fill = GOLD if dark else "#8a6813"
    frame_op = "0.32" if dark else "0.45"
    tag_op = "0.55" if dark else "0.62"
    body = mark(gold="url(#dg)").split(">", 1)[1].rsplit("</svg>", 1)[0]
    x0 = 380
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
        f'width="{W}" height="{H}" role="img" '
        f'aria-label="Yusuf Gadelrab — software, security tooling, ML systems">'
        f'<rect width="{W}" height="{H}" fill="{ground}"/>'
        f'<rect x="12" y="12" width="{W - 24}" height="{H - 24}" fill="none" '
        f'stroke="{GOLD}" stroke-width="1" opacity="{frame_op}"/>'
        f'<g transform="translate(84 52)">{body}</g>'
        f'<text x="{x0}" y="156" font-family="Georgia,\'Times New Roman\',serif" '
        f'font-size="64" font-weight="700" letter-spacing="6" fill="{name_fill}">'
        "YUSUF GADELRAB</text>"
        f'<line x1="{x0}" y1="188" x2="{x0 + 700}" y2="188" stroke="{GOLD}" '
        f'stroke-width="1.5" opacity="0.8"/>'
        f'<text x="{x0}" y="234" font-family="Georgia,serif" font-size="23" '
        f'letter-spacing="5" fill="{tag_fill}">SOFTWARE · SECURITY TOOLING · ML SYSTEMS</text>'
        f'<text x="{x0}" y="276" font-family="Georgia,serif" font-size="19" '
        f'letter-spacing="2" fill="{name_fill}" opacity="{tag_op}">'
        "San José State University · Computer Science · Class of 2028</text>"
        "</svg>"
    )


if __name__ == "__main__":
    for name, dark in (("banner-dark.svg", True), ("banner-light.svg", False)):
        path = os.path.join(HERE, name)
        with open(path, "w") as fh:
            fh.write(banner(dark))
        print("wrote", path)
